server:
  port: 8001
spring:
  application:
    name: microcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb8001
    username: root
    password: '{cipcher}85b6e595e7702d5a432967afed4ee999b5f598cabd022350e48734f8494e62dd'
    dbcp2:
      min-idle: 50
      initial-size: 50
      max-total: 50
      max-wait-millis: 200
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: org.ywl.cloud.service

eureka:
  client:
    service-url:
      defaultZone: http://eroot:eroot@eureka7001.com:7001/eureka
  instance:
    instance-id: microcloud-provider-dept-8001 #在信息列表时显示主机名称
    prefer-ip-address: true #在访问列表时显示IP地址
    lease-renewal-interval-in-seconds: 30 #向服务器发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 90 #表示90S内 没有心跳 即认为该服务停用
feign:
  hystrix:
    enabled: true
