spring:
  profiles:
    active: 
     - dev
---
server:
 port: 8101
spring:
  profiles: dev
  application:
    name: microcloud-config-clent-dev
eureka:
  client:
    service-url:
      defaultZone: http://eroot:eroot@eureka7001.com:7001/eureka
info:
 app.name: ywl.cn
 company.name: www.ywl.com
 app.version: 1.0
---
server:
  port: 8102
spring:
  profiles: beta
  application:
    name: microcloud-config-clent-beta
eureka:
  client:
    service-url:
      defaultZone: http://eroot:eroot@eureka7001.com:7001/eureka
info:
 app.name: 111111111
 company.name: www.ywl.com
 app.version: 1.0
---
server:
  port: 8103
spring:
  profiles: pro
  application:
    name: microcloud-config-clent-pro
eureka:
  client:
    service-url:
      defaultZone: http://eroot:eroot@eureka7001.com:7001/eureka
info:
 app.name: ywl.cn
 company.name: www.ywl.com
 app.version: 1.0
